---
collections:
  - name: community.crypto
    version: 3.0.5
  - name: community.general
    version: 12.3.0
  - name: ansible.posix
    version: 2.1.0
  - name: kubernetes.core
    version: 6.3.0
  - name: community.docker
    version: 5.0.6
  - name: community.vmware
    version: 6.2.0
  - name: awx.awx
    version: 24.6.1
  - name: community.hashi_vault
    version: 7.1.0
  - name: ansible.netcommon
    version: 8.4.0
