---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/platform-engineering-showcase/refs/heads/main/taskfiles/git.yaml

# PRECONDITION TO CHECK IF THE VIRTUAL ENVIRONMENT IS ACTIVATED
venv-precondition: &venv
  - sh: |
      pip -V | grep '.venv' >/dev/null 2>&1
    msg: "The pip version output does not contain .venv, Halting. Run task setup-molecule and/or source .venv/bin/activate"

tasks:
  run-molecule:
    desc: "Run molecule tests"
    preconditions: *venv
    cmds:
      - molecule test -s default

  setup-molecule:
    desc: "Setup python virtual environment"
    preconditions: *venv
    cmds:
      - pip install -U setuptools pip 'molecule'
      - pip install molecule-docker
      - molecule --version

  setup-venv:
    desc: "Setup python virtual environment"
    cmds:
      - rm -rf ./venv
      - python3 -m venv ./venv
      - echo "Don't forget to run\nsource ./venv/bin/activate"

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"
