---
- name: Install os-requirements
  ansible.builtin.include_tasks: os-requirements.yaml

- name: Install message of the day
  ansible.builtin.include_tasks: install-motd.yaml
  when: install_motd|bool

- name: Install os-packages
  ansible.builtin.include_tasks: os-packages.yaml
  when: os_packages is defined or update_packages | bool

- name: Install python modules
  ansible.builtin.include_tasks: python-modules.yaml
  when: python_modules is defined

- name: Install ansible collections
  ansible.builtin.include_tasks: ansible-collections.yaml
  when: ansible_collections is defined and ansible_collections.values()|length > 0
