---
- include_tasks: os-requirements.yaml
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- include_tasks: os-packages.yaml
  when: os_packages is defined

- include_tasks: python-modules.yaml
  when: python_modules is defined
