---
- include_tasks: os-requirements.yaml
  
- include_tasks: os-packages.yaml
  when: os_packages is defined

- include_tasks: python-modules.yaml
  when: python_modules is defined

- include_tasks: python-modules.yaml
  when: ansible_collections is defined and ansible_collections.values()|length > 0


