---
- name: Update all packages
  ansible.builtin.package:
    name: '*'
    state: latest
  tags: update
  when:
    - update_packages|bool
  register: os_update

- name: Update apt-get repo and cache
  tags: update
  community.general.apk:
    upgrade: dist
  when: update_packages|bool and ansible_os_family == 'Debian'

- name: Install os packages
  ansible.builtin.package:
    name: "{{ os_packages }}"
    state: present
  tags: install
  when:
    - os_packages is defined

# - name: Reboot machine to apply kernel updates
#   ansible.builtin.reboot:
#     reboot_timeout: 3600
#   when: os_update.changed
