---
- name: update all packages
  package:
    name: '*'
    state: latest
  tags: update
  when: update_packages | bool and not yum_fix 

- name: update apt-get repo and cache
  tags: update
  apt:
    upgrade: dist
  when: update_packages | bool and ansible_distribution == 'Debian'

- name: install os packages
  package: 
    name: "{{ os_packages }}"
    state: present
  tags: install
  when: os_packages is defined and not yum_fix

# CentOS7 and RHEL 7 fix

- name: legacy - update all packages
  yum:
    name: '*'
    state: latest
  tags: update
  when: update_packages | bool and yum_fix | bool

- name: legacy - install os packages
  yum: 
    name: "{{ os_packages }}"
    state: present
  tags: install
  when: os_packages is defined and yum_fix | bool