---
- name: update all packages
  ansible.builtin.package:
    name: '*'
    state: latest
  tags: update
  when: 
    - update_packages|bool
    - (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '8' or ansible_distribution == 'Ubuntu'

- name: update apt-get repo and cache
  tags: update
  ansible.builtin.apt:
    upgrade: dist
  when: update_packages|bool and ansible_distribution == 'Ubuntu'

- name: install os packages
  ansible.builtin.package: 
    name: "{{ os_packages }}"
    state: present
  tags: install
  when:
    - os_packages is defined
    - (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '8' or ansible_distribution == 'Ubuntu'

# CentOS7 and RHEL 7 fix

- name: legacy - update all packages
  shell: yum -y update
  tags: update
  when: 
    - update_packages|bool
    - (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '7'

- name: legacy - install os packages
  shell: "yum -y install {{ item }}"
  with_items:
    - "{{ os_packages }}"
  tags: install
  when: 
    - os_packages is defined
    - (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '7'