---
- debug:
    msg: "System {{ python_version }}"
    
- name: install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  package: 
    name: "{{ required_repo }}"
    state: present
  tags: install
  when: python_version == 2
  
- name: install the latest version of Apache
  dnf:
    name: "{{ required_repo }}"
    state: present
  tags: install
  when: python_version == 3