---
- name: Add epel rpm key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ epel_rpm_key }}"
  when: update_packages|bool and ansible_distribution != 'Rocky' and ansible_distribution != 'Ubuntu' and ansible_distribution != 'RedHat'

- name: Add epel for RHEL9
  ansible.builtin.shell: |
    subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  when: ansible_distribution == 'RedHat'

- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: true
  when: update_packages|bool and ansible_distribution == 'Ubuntu'

- name: "Install required repo for {{ ansible_distribution }} {{ ansible_distribution_version }}"
  ansible.builtin.package:
    name: "{{ required_repo }}"
    state: present
  tags: install
  ignore_errors: true
