---
- name: install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  package: 
    name: "{{ required_repo }}"
    state: present
  when:
    - ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
    - ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'
  tags: install

# CentOS7 and RHEL 7 fix

- name: legacy - install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  yum: 
    name: "{{ required_repo }}"
    state: present
  when:
    - ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
    - ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
  tags: install