---
- name: Add epel rpm key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ epel_rpm_key }}"
  when: update_packages|bool and ansible_distribution != 'Rocky'

- name: update apt-cache
  ansible.builtin.apt:
    update_cache: yes
  when: update_packages|bool and ansible_distribution == 'Ubuntu'

- name: install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  ansible.builtin.package:
    name: "{{ required_repo }}"
    state: present
  tags: install
  ignore_errors: true
