---
- name: install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  package: 
    name: "{{ required_repo }}"
    state: present
  when: ansible_distribution == "CentOS"
  tags: install