---
- name: install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  package: 
    name: "{{ required_repo_centos }}"
    state: present
  when: ansible_distribution == "CentOS"
  tags: install
  
- name: install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  package: 
    name: "{{ required_repo_rhel7 }}"
    state: present
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == 7
  tags: install