---
- name: update apt-cache
  ansible.builtin.apt:
    update_cache: yes
  when: update_packages|bool and ansible_distribution == 'Ubuntu'

- name: install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  ansible.builtin.package: 
    name: "{{ required_repo }}"
    state: present
  when:
    - (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '8'
  tags: install

- name: legacy - install required repo for "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  shell: "yum -y install {{ required_repo }}"
  when:
    - (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '7'
  tags: install
  