---
- name: update all packages
  package:
    name: '*'
    state: latest
  tags: update
  when: update_packages | bool

- name: Update apt-get repo and cache
  tags: update
  apt:
    upgrade: dist
  when: update_packages | bool and ansible_distribution == 'Debian'

- name: "Install os package"
  package: 
    name: "{{ item.name }}"
    state: present
  loop: "{{ os_packages }}"
  tags: install