---
- name: update all packages
  package:
    name: '*'
    state: latest
  tags: update
  when: update_packages | bool

- name: update apt-get repo and cache
  tags: update
  apt:
    upgrade: dist
  when: update_packages | bool and ansible_distribution == 'Debian'

- name: "install os package"
  package: 
    name: "{{ lookup('item.name', wantlist=True) }}"
    state: present
  loop: "{{ os_packages }}"
  tags: install
  when: os_packages is defined