---
- name: make sure pip2 is installed
  package:
    name: python2
    state: present
  when: ansible_python.version.major==2

- name: make sure pip3 is installed
  package:
    name: python3-pip
    state: present
  when: ansible_python.version.major==3

- pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    executable: /usr/bin/pip{{ python_version }}
    state: "{{ state }}"
  loop: "{{ pip_modules }}"