---
- name: update all packages
  yum:
    name: '*'
    state: latest
  tags: update
  when: update_packages | bool

- name: update apt-get repo and cache
  tags: update
  apt:
    upgrade: dist
  when: update_packages | bool and ansible_distribution == 'Debian'

- name: install os packages
  yum: 
    name: "{{ os_packages }}"
    state: present
  tags: install
  when: os_packages is defined