---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  vars:
    update_packages: true
    os_packages:
      - htop
      - unzip
    python_modules:
      - name: kubernetes
        version: 10.0.1
      - name: openshift

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - unzip
        - tar

  tasks:
    - name: Start install_requirements
      ansible.builtin.include_role:
        name: install-requirements
