---
name: Release Ansible Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Tag name for the release'
        required: true
        type: string
      release-message:
        description: 'Release message/notes'
        required: true
        type: string

jobs:
  release-ansible:
    name: Release
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-release-module.yaml@main
    with:
      module-name: install-requirements
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: k8s
      archive-kind: tar.gz
      runs-on: ghr-install-requirements-in-cluster
      continue-error: false
